version: '3.8'
services:
  neutron-snapshot:
    image: neutron-mainnet-snapshot
    container_name: neutron-mainnet-snapshot
    volumes:
      - ./snapshot/:/opt/neutron/snapshot
    environment:
      - RPC_NODE=https://neutron-rpc.polkachu.com:443
      - INTERVAL=1000
      - NEUTROND_P2P_MAX_NUM_OUTBOUND_PEERS=500
      - NEUTROND_P2P_MAX_NUM_INBOUND_PEERS=500

  neutron-fork:
    image: neutron-mainnet-fork
    container_name: neutron-mainnet-fork
    volumes:
      - ./snapshot/:/opt/neutron/snapshot
      - ./custom/:/opt/neutron/custom
      - ./current_data:/opt/neutron/data
    environment:
      - MAIN_WALLET=neutron1kyn3jx88wvnm3mhnwpuue29alhsatwzrpkwhu6
      - VALIDATOR=val_a
      - FIRST_RUN=true
      - GENERATE_GENESIS=true
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 26660:26660

  neutron-fork-genesis:
    image: neutron-mainnet-fork
    container_name: neutron-mainnet-fork-3
    volumes:
      - ./snapshot/:/opt/neutron/snapshot
      - ./custom/:/opt/neutron/custom
      - ./current_data:/opt/neutron/data
      - ./genesis:/opt/neutron/genesis
    environment:
      - MAIN_WALLET=neutron1kyn3jx88wvnm3mhnwpuue29alhsatwzrpkwhu6
      - VALIDATOR=val_a
      - FIRST_RUN=true
      - GENERATE_GENESIS=false
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 26660:26660

  neutron-fork-continue:
    image: neutron-mainnet-fork
    container_name: neutron-mainnet-fork-2
    volumes:
      - ./snapshot/:/opt/neutron/snapshot
      - ./custom/:/opt/neutron/custom
      - ./current_data:/opt/neutron/data
    environment:
      - MAIN_WALLET=neutron1kyn3jx88wvnm3mhnwpuue29alhsatwzrpkwhu6
      - VALIDATOR=val_a
      - FIRST_RUN=false
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 26660:26660

  neutron-fork-upgrade:
    image: neutron-mainnet-fork
    container_name: neutron-mainnet-fork-4
    volumes:
      - ./snapshot/:/opt/neutron/snapshot
      - ./custom/:/opt/neutron/custom
      - ./current_data:/opt/neutron/data
    environment:
      - MAIN_WALLET=neutron1kyn3jx88wvnm3mhnwpuue29alhsatwzrpkwhu6
      - VALIDATOR=val_a
      - FIRST_RUN=false
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 26660:26660
    command: bash /opt/neutron/start_upgraded_neutron.sh

  oracle:
    image: skip-mev/slinky-e2e-oracle
    entrypoint: [
      "slinky",
      "--oracle-config-path",
      "/oracle/oracle.json",
      # "--market-config-path",
      # "/oracle/market.json",
      ]
    ports:
      - "8080:8080" # main oracle port
      - "8002:8002" # oracle metrics port
