version: '3.8'
services:
  celestia-fork:
    image: celestia-mainnet-fork
    container_name: celestia-mainnet-fork
    volumes:
      - ./snapshot/:/opt/celestia/snapshot
      - ./custom/:/opt/celestia/custom
    environment:
      - MAIN_WALLET=celestia1473jqhjtz36zplpdhguyghma7uya2cf00r8c7t
      # it's possible to create valoper with predefine3d mnemonic with VAL_MNEMONIC env var
      # - VAL_MNEMONIC=""
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 9090:9090
    networks:
      - devnet_network
    mem_limit: 60g
    memswap_limit: 156g

  oracle:
    image: skip-mev/slinky-e2e-oracle
    container_name: oracle
    entrypoint: [ "slinky", "--market-map-endpoint", "neutron-mainnet-fork:9090" ]
    ports:
      - "8080:8080" # main oracle port
      - "8002:8002" # oracle metrics port
    networks:
      - devnet_network

networks:
  devnet_network:
    driver: bridge
