# syntax=docker/dockerfile:1

FROM golang:1.22-bullseye
RUN apt-get update && apt-get install -y jq curl git
RUN git clone --branch v4.2.3 https://github.com/neutron-org/neutron.git /opt/neutron
WORKDIR /opt/neutron

RUN make install

RUN neutrond init test --chain-id=neutron-1 --home /opt/neutron/data
ADD https://raw.githubusercontent.com/neutron-org/mainnet-assets/main/neutron-1-genesis.json /opt/neutron/data/config/genesis.json
ADD https://snapshots.polkachu.com/addrbook/neutron/addrbook.json /opt/neutron/data/config/addrbook.json
COPY --chmod=0755 ./scripts/get_state_sync.sh /opt/neutron/get_state_sync.sh

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD \
    curl -f http://127.0.0.1:1317/blocks/1 >/dev/null 2>&1 || exit 1

CMD /opt/neutron/get_state_sync.sh
