[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001


[[chains]]
type = "CosmosSdk"
id = "neutron-1"
rpc_addr = "http://neutron-mainnet-fork:26657"
grpc_addr = "http://neutron-mainnet-fork:9090"
event_source = { mode = "push", url = "ws://neutron-mainnet-fork:26657/websocket", batch_delay = '500ms' }
rpc_timeout = "10s"
account_prefix = "neutron"
key_name = "neutron-key"
store_prefix = "ibc"
default_gas = 5000000
max_gas = 25000000
gas_price = { price = 0.01, denom = 'untrn' }
gas_multiplier = 2
dynamic_gas_price = { enabled = true, multiplier = 1.5, max = 0.05 }
max_msg_num = 20
max_tx_size = 180000
max_block_time = "3s"
clock_drift = "3s"
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
key_store_type = "Test"

[[chains]]
type = "CosmosSdk"
id = "celestia"
rpc_addr = "http://celestia-mainnet-fork:26657"
grpc_addr = "http://celestia-mainnet-fork:9090"
event_source = { mode = "push", url = "ws://celestia-mainnet-fork:26657/websocket", batch_delay = '500ms' }
rpc_timeout = "10s"
trusted_node = false
account_prefix = "celestia"
key_name = "celestia-key"
store_prefix = "ibc"
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "10s"
max_block_time = "13s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
sequential_batch_tx = false
allow_ccq = true
gas_price = { price = 0.02, denom = 'utia' }
dynamic_gas_price = { enabled = false, multiplier = 1.1, max = 0.6 }
default_gas = 1000000
max_gas = 10000000
gas_multiplier = 2
trust_threshold = { numerator = '2', denominator = '3' }
compat_mode = "0.34"
key_store_type = "Test"